### ISSUE TITLE
Minimap Icon Missing

### ISSUE THREAD

**Issue by Hadwyn** [AssisrMatheus/TodoChecklister#32]
Icon was shown on character I used the addon with first, cannot get it to appear on my main.

**Comment by AssisrMatheus** [comment]
Do you remember if you have deleted any addon in the meantime? I use a library that adds the icon so maybe if that was deleted the icon won't appear. I'll try to manually add this library so this won't happen again, I'm sorry for that.

You can write "/todo tg" on chat and make a macro that does this on the time being.

**Comment by Hadwyn** [comment]
I did delete Details! Damage meter. Could be the issue.

**Comment by AssisrMatheus** [comment]
Fixed with the release of 1.2.2. Now I ensure the minimap icon library exist
