### ISSUE TITLE
FPS Drops when resizing window

### ISSUE THREAD

**Issue by amiyuy** [AssisrMatheus/TodoChecklister#33]
Testing out the resizing and duplicate entries fixes and noticed FPS hitches.

I'm not sure if it's related to how it jumped off the side there at the beginning or not.

Video: https://plays.tv/video/5d899e166e28d17536/todochecklister-test

**Comment by AssisrMatheus** [comment]
Oh thank you for the awesome video!

I'm sorry you experienced this, will fix that as soon as I get home from work. This DEFINITELY should not happen

**Comment by AssisrMatheus** [comment]
Fixed with the release of 1.2.2

**Comment by AssisrMatheus** [comment]
@amiyuy could you please try it again with the new version?

**Comment by amiyuy** [comment]
Seems good, with 1.2.3.  Thanks!
